use geolonia maps style.json
geolonia/cdn.geolonia.com pull request #37
Opened 2022-01-06 08:52 UTC by naogify

close #36 

`npm run build:styles` 実行時に、`https://github.com/geoloniamaps/<スタイル名>/tree/gh-pages/style.json ` から `style.json` をダウンロードして、`cdn.geolonia.com/public/style/geolonia/スタイル名/` に日・英版のスタイルコピーするように修正しました。

気になる点

[styles.json](https://github.com/geolonia/cdn.geolonia.com/blob/use-geoloniamaps/public/style/styles.json) で指定する値を、`geolonia/basic` から `basic` に変更したので、embed api スタイル指定形式に影響があれば、指摘頂けると嬉しいです。

```
[
  "basic",
  "gsi",
  "midnight",
  "red-planet",
  "notebook",
  "homework"
]
```
embed api を見た所、styles.json を参照していなかったので影響はないと思いますが、何かあれば指摘いただけますと!
https://github.com/geolonia/embed/blob/master/src/lib/util.js#L173-L184

2022-01-06 09:11 UTC, naogify commented
> 気になる点
> 
> styles.json で指定する値を、geolonia/basic から basic に変更したので、embed api スタイル指定形式に影響があれば、指摘頂けると嬉しいです。
> 
> [
>   "basic",
>   "gsi",
>   "midnight",
>   "red-planet",
>   "notebook",
>   "homework"
> ]
> embed api を見た所、styles.json を参照していなかったので影響はないと思いますが、何かあれば指摘いただけますと!
> https://github.com/geolonia/embed/blob/master/src/lib/util.js#L173-L184

上で書いていた気になる点は、get-geolonia で styles.json を使っていることが分かったので、geolonia/basic 形式で指定するように修正しました! なので問題なくなりました。

https://github.com/geolonia/get-geolonia/blob/dea6bdba2346b5e226e260d1b24573a2b1c90ef5/src/stylesControl.js#L17

2022-01-06 09:24 UTC, kamataryo commented on bin/build-styles.js
> +  style = style.replace('geolonia/', '')
@naogify ありがとうございます！geolonia -> geoloniamap というのが例外的な扱いになるので、その旨コメントだけ入れておいていただけたらいいかと思いました。

2022-01-06 09:25 UTC, kamataryo requested changes
一点コメントしました🙇 
https://github.com/geolonia/cdn.geolonia.com/pull/37/files#r779408399

2022-01-07 01:59 UTC, naogify commented
@keichan34 @kamataryo 

それぞれのブランチにあるスタイルを `master` ディレクトリと `use-charites` に配置して、diff を実行してみました。
結果、各スタイルは `metadata` と `id` が削除されているだけという事が確認できました。


```
diff -r master/gsi/en.json use-charites/gsi/en.json
4d3
<   "metadata": {},
4938,4939c4937
<   ],
<   "id": "geolonia-gsi"
---
>   ]
diff -r master/homework/en.json use-charites/homework/en.json
4d3
<   "metadata": {},
302,303c301
<   ],
<   "id": "geolonia-homework"
---
>   ]
diff -r master/midnight/en.json use-charites/midnight/en.json
4d3
<   "metadata": {},
3039,3040c3038
<   ],
<   "id": "geolonia-midnight"
---
>   ]
diff -r master/notebook/en.json use-charites/notebook/en.json
4d3
<   "metadata": {},
3064,3065c3063
<   ],
<   "id": "geolonia-notebook"
---
>   ]
diff -r master/red-planet/en.json use-charites/red-planet/en.json
4d3
<   "metadata": {},
3057,3058c3056
<   ],
<   "id": "geolonia-red-planet"
---
>   ]

```

2022-01-07 02:13 UTC, kamataryo approved these changes
ありがとうございます。問題なさそうですね！

2022-01-07 04:01 UTC, keichan34 approved these changes
ありがとうございました

2022-01-07 07:45 UTC, merged